In [17]:
import numpy as np

In [50]:
array = np.arange(10)
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
odd = [num for num in array if num % 2 != 0]
odd

[1, 3, 5, 7, 9]

In [8]:
replace = [100 if num % 2 != 0 else num for num in array]
replace

[0, 100, 2, 100, 4, 100, 6, 100, 8, 100]

In [10]:
replace_1 = [-1 if num % 2 != 0 else num for num in array]
replace_1

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

In [21]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
array2 = array1.reshape(2, -1)
array2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
A = np.array([2, 6, 1, 9, 10, 3, 27])
B = A[(A >= 5) & (A <= 10)]
B


array([ 6,  9, 10])

In [22]:
array2 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

b = array2.reverse()
b

AttributeError: ignored

In [28]:
rand_arr = np.random.uniform(5, 10, size=(5, 3))

rand_arr


array([[8.325558  , 9.90889695, 5.18035836],
       [5.54754246, 7.86251671, 8.46140045],
       [9.24983937, 5.22510582, 9.30227939],
       [9.67715832, 7.48349639, 9.16690013],
       [5.30944685, 9.32693633, 6.25272057]])

In [29]:
mean = np.mean(rand_arr)
mean

1.7219425736798617

In [30]:
median = np.median(rand_arr)
median

8.325558001510043

In [31]:
sd = np.std(rand_arr)
sd

1.7219425736798617

In [34]:
scores = np.array([
    [80, 90, 92, 88],
    [85, 97, 90, 87],
    [82, 83, 87, 81]
])


    subject_scores = scores[:, i]
    fifth_percentile = np.percentile(subject_scores, 5)
    ninetyfifth_percentile = np.percentile(subject_scores, 95)
    f"For {subject}: 5th percentile = {fifth_percentile}, 95th percentile = {ninetyfifth_percentile}"


IndentationError: ignored

In [38]:
all_scores = np.unique(scores.flatten())
sorted_scores = np.sort(all_scores)
second_highest = sorted_scores[-2]

second_highest


92

In [40]:
np.random.seed(100)
A = np.random.uniform(1, 50, 20)

A = np.clip(A, 10, 30)
A


array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [41]:
array_of_arrays = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

flat_array = array_of_arrays.flatten()
flat_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.random.seed(100)
A = np.random.randint(1, 10, [5, 3])
A

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [44]:
max = np.max(A, 1)

max

array([9, 8, 6, 3, 9])

In [45]:
array = np.arange(5, 5 + 3 * 10, 3)
array

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [49]:
array = np.array([[1, 3, 5, 7],
                   [9, 11, 13, 15],
                   [2, 4, 6, 8]])

slicee = array[0:2, 0:2]
slicee

array([[ 1,  3],
       [ 9, 11]])